"""empty message

Revision ID: da34fa0db566
Revises: 0f1c8401ea38
Create Date: 2023-04-20 22:22:09.752998

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'da34fa0db566'
down_revision = '0f1c8401ea38'
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.create_table('answer_for_board',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('answer', sa.VARCHAR(length=500), nullable=False),
    sa.Column('answer_writer', sa.VARCHAR(length=60), nullable=True),
    sa.Column('article_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['article_id'], ['board.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('userinformation',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('username', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('nickname', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('password', mysql.VARCHAR(length=150), nullable=False),
    sa.Column('email', mysql.VARCHAR(length=150), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('username', 'userinformation', ['username'], unique=False)
    op.create_index('nickname', 'userinformation', ['nickname'], unique=False)
    op.create_index('name', 'userinformation', ['name'], unique=False)
    op.create_index('email', 'userinformation', ['email'], unique=False)
    op.create_table('replies',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('content', mysql.VARCHAR(length=500), nullable=False),
    sa.Column('writer', mysql.VARCHAR(length=500), nullable=False),
    sa.Column('write_date', mysql.DATETIME(), nullable=False),
    sa.Column('video_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['video_id'], ['dance_dataset.id'], name='replies_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('dance_dataset',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('singer', mysql.VARCHAR(length=500), nullable=False),
    sa.Column('src', mysql.VARCHAR(length=500), nullable=False),
    sa.Column('youtube_url', mysql.VARCHAR(length=500), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('answer_for_board')
    op.drop_table('Replies')
    op.drop_table('UserInformation')
    op.drop_table('Dance_dataset')
    # ### end Alembic commands ###
